version: '3.1'

services:
#   grafana:
#     image: grafana/grafana:8.4.4
#     container_name: grafana
#     ports:
#       - 3000:3000
#     links:
#       - postgres
#     env_file:
#       - ./grafana/config.monitoring
#     volumes:
#       - ./grafana/dashboard:/etc/extra-config/grafana
#     command: ./etc/extra-config/grafana/post.sh
  # we will use postgres as datasource.
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - 5432:5432                 # Postgres port
    volumes:
      - ./postgres/sql:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecure
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050