version: '3.1'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    depends_on:
        - postgres
    ports:
        - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    env_file: environment/.env
  postgres:
    container_name: postgres
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres       
    ports:
      - 5432:5432                 
    volumes:
      - ./postgres/sql:/docker-entrypoint-initdb.d
    env_file: 
      - environment/.env
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecure
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050

volumes:
  grafana-storage: